# Generated by Django 5.0.1 on 2024-07-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('subscriber_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID do Assinante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-priority', '-created_at', 'status'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='subscriber_id',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Entrega'), ('takeout', 'Retirada')], default='takeout', max_length=16, verbose_name='Modo de Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('credit_card', 'Crédito'), ('debit_card', 'Dábito'), ('pix', 'Pix')], default='pix', max_length=16, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=8, verbose_name='Valor Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.TextField(blank=True, verbose_name='Detalhes do Pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='ID do Assinante'),
            preserve_default=False,
        ),
    ]
